trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
  displayName: "Build and Test"
  jobs:
    - job: Api_Asset_Management_NestJS
      displayName: "Lint, Test, and Audit NestJS"
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: "20.x"
          displayName: "Install Node.js"

        - script: |
            cd BE
            npm install -g @nestjs/cli
            npm install
          displayName: "Install dependencies"

        - script: |
            cd BE
            npm run lint
          displayName: "Run lint"

        - script: |
            cd BE
            npm run gitleaks
          displayName: "Run GitLeaks"

        - script: |
            cd BE
            npm run test:cov
          displayName: "Run tests"

        - script: |
            cd BE
            npm audit --audit-level=high
          displayName: "Run npm audit"
          continueOnError: true

        - script: |
            cd BE
            npm run build
          displayName: "Build project"

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: "BE/dist"
            ArtifactName: "drop"
            publishLocation: "Container"
          displayName: "Publish build artifacts"

- stage: Deploy
    displayName: "Deploy to Azure Web App"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        displayName: "Deploy Job"
        environment: "yourAzureWebAppEnvironmentName"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    appName: 'yourWebAppName'
                    package: "$(Pipeline.Workspace)/drop"
                    runtimeStack: 'NODE|20.x'
                    startUpCommand: 'npm run start:prod'