name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  IMAGE_REPOSITORY: 'assetmanagementbe'
  DOCKERFILE_PATH: './Dockerfile'
  TAG: '${{ github.run_id }}'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm install -g @nestjs/cli
          npm install
          npm run prisma:generate

      - name: Run lint
        run: npm run lint

      - name: Run GitLeaks
        run: npm run gitleaks

      - name: Run tests
        run: npm run test:ci

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/test-report.xml'

      - name: Publish code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage/cobertura-coverage.xml

      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Build project
        run: npm run build

  deploy:
    name: Build and Push Docker Image
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_REPOSITORY }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_REPOSITORY }}:${{ env.TAG }}